# Generated by Django 2.1 on 2018-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('diagnosis_text',),
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('symptom_text',),
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_text', models.CharField(max_length=2000)),
                ('diagnoses', models.ManyToManyField(to='health.Diagnosis')),
            ],
            options={
                'ordering': ('treatment_text',),
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(to='health.Symptom'),
        ),
    ]
