# Generated by Django 2.1 on 2019-01-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('location_text',),
            },
        ),
        migrations.AddField(
            model_name='symptom',
            name='location',
            field=models.ManyToManyField(to='health.Location'),
        ),
    ]
