# Generated by Django 2.1 on 2019-01-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20190110_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='location',
            new_name='locations',
        ),
    ]
